### ISSUE TITLE
Block specific module

### ISSUE THREAD

**Issue by Mimanolis** [GreenMeteor/humhub-block-modules#4]
Hi, appreciate your contribution to the platform. Can you tell me how to block a specific module from apperaring for installation when a user creates a space?

**Comment by ArchBlood** [comment]
Currently the following can be done for activation of some modules for space and user profiles, otherwise you will have to block a module similar to #3
![Screenshot_1](https://github.com/GreenMeteor/block/assets/35392110/f830f5d1-f3e2-44e7-b144-0176bfdb2d5e)
